name: Test Workout Tracker API

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run API
        run: |
          npx ts-node src/server/api.ts & sleep 5
          curl -X GET http://localhost:3000/workouts || echo "Server test failed"
